# Custom Language File for Launcher Customizer

[ejs.app]
title = "츄르 놀이터"

[ejs.landing]
mediaGitHubURL = "https://github.com/mycha0216/chur"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/churr"

[ejs.settings]
sourceGithubLink = "https://github.com/mycha0216/chur"
supportLink = "https://github.com/mycha0216/chur/issues"

[ejs.welcome]
welcomeHeader = "츄르 놀이터에 오신 것을 환영합니다."
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
